### ISSUE TITLE
Setup CI hooks on dev branch

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/CSM-CameraModel#121]
With Master becoming our stable release branch and dev becoming the "dev" branch, we need to add CI hooks to dev so that it runs tests and then if successful, pushes a dev build to Anaconda.

**Comment by jlaura** [comment]
Fixed this morning. We now have a build string in the dev meta.yml that defines the package as `name-version-dev`. The dev package is downloadable using the `dev` label.

For `master`: Force uploads are currently **off**. Therefore, we have to increment the build number in order to get the files uploaded to anaconda cloud.
For `dev`: Force uploads are currently **on**. This ensures that any merged (and passing) PRs onto dev are automatically propagated up to anaconda cloud. This makes dev the bleeding edge installation at all times.
