### ISSUE TITLE
Generic line scan camera does not correctly calculate sub-pixel look vectors

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/CSM-CameraModel#26]
The `losToEcf` method in the generic line scan camera model computes a look vector from an image coordinate.  It correctly accounts for fractional samples, but it doesn't account for fractional lines. Regardless of what the entered line value is, it is always assumed to be the center of the nearest line.

This method is used in both image to ground and ground to image.

**Comment by jessemapel** [comment]
Time for fractional lines is also calculated incorrectly. This should be calculated to the nearest whole pixel. Right now, time is being calculated as though it was linear/piecewise-linear down the image. It really should be a step function.

**Comment by thareUSGS** [comment]
Per Randy, for losRoEcf -- computing look vectors to the nearest whole line is certainly not the desired behavior.  We need to match features to subpixel so we need to compute locations to sub-line precision for sure.  Especially since the stereobase is in the line direction.  Might get away with it for HiRISE I suppose.

For the second I don't think he agrees and stated, fractional time should map smoothly to fractional line and vice versa, not be rounded off.
